from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from datetime import datetime


def generate_audit_report(output_path: str, data: dict):
    """
    Aeterna – Integrity Reference Certificate
    Cryptographic Integrity Reference Report
    """

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()
    story = []

    # -----------------------------
    # Title
    # -----------------------------
    title_style = ParagraphStyle(
        "TitleStyle",
        fontSize=18,
        spaceAfter=12,
        alignment=1
    )

    subtitle_style = ParagraphStyle(
        "SubtitleStyle",
        fontSize=10,
        spaceAfter=24,
        alignment=1,
        textColor=colors.grey
    )

    story.append(Paragraph("AETERNA – INTEGRITY REFERENCE CERTIFICATE", title_style))
    story.append(Paragraph(
        "Cryptographic Integrity Reference Report",
        subtitle_style
    ))

    # -----------------------------
    # Executive Summary
    # -----------------------------
    story.append(Paragraph("Executive Summary", styles["Heading2"]))

    summary_text = (
        f"This report documents a cryptographic integrity reference generated by Aeterna "
        f"at a specific point in time.<br/><br/>"
        f"A deterministic SHA3-512 hash was computed for the provided deliverable and "
        f"recorded together with contextual metadata supplied by the user.<br/><br/>"
        f"<b>VERDICT: {data.get('verdict')}</b><br/><br/>"
        f"This certificate attests exclusively to the integrity of the referenced "
        f"deliverable at the reported timestamp."
    )

    story.append(Paragraph(summary_text, styles["BodyText"]))
    story.append(Spacer(1, 16))

    # -----------------------------
    # System Identification
    # -----------------------------
    story.append(Paragraph("System Identification", styles["Heading2"]))

    system_table = Table([
        ["Instance ID", data.get("instance_id")],
        ["Customer", data.get("customer")],
        ["License Type", data.get("license_type")],
        ["Declared Scope", data.get("scope")]
    ], colWidths=[160, 320])

    system_table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, 0), (0, -1), colors.whitesmoke),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE")
    ]))

    story.append(system_table)
    story.append(Spacer(1, 16))

    # -----------------------------
    # Verification Details
    # -----------------------------
    story.append(Paragraph("Verification Details", styles["Heading2"]))

    verification_text = (
        f"A total of <b>{data.get('checked_events')}</b> integrity records were evaluated "
        f"to generate a deterministic hash reference for the deliverable.<br/><br/>"
        f"The verification process is deterministic: any alteration to the referenced "
        f"deliverable would result in a different hash and fail integrity verification."
    )

    story.append(Paragraph(verification_text, styles["BodyText"]))
    story.append(Spacer(1, 16))

    # -----------------------------
    # Scope Monitoring
    # -----------------------------
    story.append(Paragraph("Scope Monitoring and Control", styles["Heading2"]))

    scope_text = (
        "Aeterna records the declared scope and user-provided context associated with the "
        "deliverable at the time the integrity reference is generated.<br/><br/>"
        "<b>No claims are made beyond the recorded scope and the deterministic hash reference.</b>"
    )

    story.append(Paragraph(scope_text, styles["BodyText"]))
    story.append(Spacer(1, 16))

    # -----------------------------
    # Technical Assurance
    # -----------------------------
    story.append(Paragraph("Technical Assurance", styles["Heading2"]))

    technical_text = (
        "Aeterna computes a deterministic cryptographic fingerprint using "
        "<b>SHA3-512 hashing</b> and binds it to the provided metadata at the time of "
        "generation.<br/><br/>"
        "Any modification of the referenced deliverable after the reported timestamp "
        "produces a different hash and fails integrity verification.<br/><br/>"
        "This report attests exclusively to <b>cryptographic integrity reference</b>. "
        "It does not assert the correctness, legality, or semantic validity of the underlying data."
    )

    story.append(Paragraph(technical_text, styles["BodyText"]))
    story.append(Spacer(1, 16))

    # -----------------------------
    # Deliverable Evidence Record
    # -----------------------------
    story.append(Paragraph("Deliverable Evidence Record", styles["Heading2"]))

    # Estilo monoespaciado con wrapping correcto
    hash_style = ParagraphStyle(
    "HashStyle",
    fontName="Courier",
    fontSize=8,
    leading=10,
    wordWrap="CJK"   # Permite que hashes largos se ajusten en la celda
  )

    deliverable_hash = data.get("deliverable_hash", "N/A")

    deliverable_table = Table([
    ["Deliverable Hash", Paragraph(deliverable_hash, hash_style)],
    ["Hash Algorithm", data.get("deliverable_hash_algorithm", "SHA3-512")],
    ["Declared By", data.get("deliverable_declared_by", "N/A")],
    ["Purpose", data.get("deliverable_purpose", "N/A")]
], colWidths=[160, 320])

    deliverable_table.setStyle(TableStyle([
    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
    ("BACKGROUND", (0, 0), (0, -1), colors.whitesmoke),
    ("VALIGN", (0, 0), (-1, -1), "MIDDLE")
]))

    story.append(deliverable_table)
    story.append(Spacer(1, 16))


    # -----------------------------
    # Evidence Integrity Statement
    # -----------------------------
    story.append(Paragraph("Evidence Integrity Statement", styles["Heading2"]))

    evidence_text = (
        "This certificate provides a cryptographic integrity reference only.<br/><br/>"
        "It does not constitute forensic evidence, a legal chain of custody, "
        "or an independent third-party verification.<br/><br/>"
        "Any use of this certificate beyond technical integrity reference "
        "is outside the scope of this document."
    )

    story.append(Paragraph(evidence_text, styles["BodyText"]))
    story.append(Spacer(1, 16))

    # -----------------------------
    # Instance Binding
    # -----------------------------
    story.append(Paragraph("Instance Binding", styles["Heading2"]))

    binding_text = (
        "This report is cryptographically bound to a specific Aeterna execution instance. "
        "The following fingerprint uniquely identifies the system instance at the "
        "time of reference generation:"
    )

    story.append(Paragraph(binding_text, styles["BodyText"]))
    story.append(Spacer(1, 8))

    fingerprint_table = Table([
        ["Instance Fingerprint", data.get("instance_fingerprint")]
    ], colWidths=[200, 280])

    fingerprint_table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, 0), (0, 0), colors.whitesmoke),
        ("FONT", (1, 0), (1, 0), "Courier")
    ]))

    story.append(fingerprint_table)
    story.append(Spacer(1, 16))

    # -----------------------------
    # Sealed Deliverable
    # -----------------------------
    story.append(Paragraph("Sealed Deliverable", styles["Heading2"]))

    deliverable_table = Table([
    ["Deliverable Hash (SHA3-512)", Paragraph(data.get("deliverable_hash", "N/A"), hash_style)],
    ["Declared By", Paragraph(data.get("deliverable_declared_by", "N/A"), styles["BodyText"])],
    ["Purpose", Paragraph(data.get("deliverable_purpose", "N/A"), styles["BodyText"])]
], colWidths=[200, 280])


    deliverable_table.setStyle(TableStyle([
    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
    ("BACKGROUND", (0, 0), (0, -1), colors.whitesmoke),
    ("FONT", (1, 0), (1, 0), "Courier"),
    ("VALIGN", (0, 0), (-1, -1), "MIDDLE")
]))
    
    story.append(deliverable_table)
    story.append(Spacer(1, 16))


    # -----------------------------
    # Cryptographic Attestation
    # -----------------------------
    story.append(Paragraph("Cryptographic Reference", styles["Heading2"]))

    reference_text = (
        "The values below are internal reference artifacts used to verify report integrity. "
        "They do not constitute a legal or external signature."
    )
    story.append(Paragraph(reference_text, styles["BodyText"]))
    story.append(Spacer(1, 8))

    mono = ParagraphStyle(
        "Mono",
        fontName="Courier",
        fontSize=9,
        spaceAfter=10
    )

    story.append(Paragraph(
        f"<b>Report Hash (SHA3-512)</b><br/>{data.get('report_hash')}",
        mono
    ))

    story.append(Paragraph(
        f"<b>Internal Reference Signature (Aeterna)</b><br/>{data.get('report_signature')}",
        mono
    ))

    # -----------------------------
    # Footer
    # -----------------------------
    footer = Paragraph(
        f"Report generated by <b>Aeterna</b><br/>"
        f"{datetime.utcnow().isoformat()} UTC<br/><br/>"
        f"Confidential – Generated for integrity reference purposes",
        styles["Italic"]
    )

    story.append(Spacer(1, 32))
    story.append(footer)

    doc.build(story)
